### ISSUE TITLE
Offering https://map.chicory.pizza

### ISSUE THREAD

**Issue by ngyikp** [JdavisBro/chicory#1]
Hey there, I own [https://chicory.pizza](https://chicory.pizza) (official Twitter [posted it 19 minutes](https://twitter.com/chicory/status/1485334683772538884) after I dropped the link in a Discord lol), I wonder maybe make the domain to be more useful by offering it to others, https://map.chicory.pizza would be a 🍕 fit :)

**Comment by JdavisBro** [comment]
okay.
